import {PHRASES,sampleDuet,returnToStart,evaluateDuet,summarizeSession,sessionQuality,identifyHands,projectHands} from './duet.mjs';
import {DotScene,FINGERS,demoPoint,fitCanvas,drawDotHand,drawTrails,TrailHistory} from './dots.mjs';
const $=id=>document.getElementById(id),state={beat:0,playing:!matchMedia('(prefers-reduced-motion: reduce)').matches,start:0,end:32,speed:.75,bpm:96,loop:true,trails:true,practice:false,counting:false,samples:[],observed:{left:null,right:null},lastDetection:0,swap:false,workerReady:false,stream:null,expected:0,elapsed:0,frameGap:0};
let scene,lastTime=performance.now(),worker,busy=false,lastFrame=0,lastSample=0,previous=null,audio=null,metro=false,lastClick=-1,noticeTimer,countTimer,returnBeat=null,cameraPromise=null,firstFrameResolve=null;
const cameraHistory=new TrailHistory(900);let connections=true,rawView=false;
const pathSamples=Array.from({length:801},(_,i)=>sampleDuet(i*.04)),pathAt=beat=>pathSamples[Math.min(800,Math.max(0,Math.round(beat/.04)))];
scene=new DotScene($('demo-canvas'));
function showNotice(text){$('notice').textContent=text;$('notice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notice').hidden=true,6500);}
function demoHistory(){const rate=state.bpm/60*state.speed,span=.9*rate,result=[];for(let age=span;age>=0;age-=.04){let t;if(returnBeat!==null)t=returnToStart(state.end,state.start,Math.max(0,returnBeat-age));else t=pathAt(Math.max(state.start,state.beat-age));result.push({time:-age/rate*1000,points:t.points});}return result;}
function renderPaths(target){for(const side of ['left','right']){const c=demoPoint(target.points[side][0]),label=$(`${side}-label`);label.style.left=`${c.x*100}%`;label.style.top=`${Math.max(15,Math.min(82,c.y*100+7))}%`;}}
function updateCamera(target){const {ctx,w,h}=fitCanvas($('camera-overlay'));ctx.clearRect(0,0,w,h);if(!state.stream)return;const now=performance.now(),fresh=now-state.lastDetection<Math.min(2000,Math.max(600,state.frameGap*1.5)),hands=fresh?state.observed:{left:null,right:null};for(const side of ['left','right']){drawDotHand(ctx,target.points[side],side,w,h,{ghost:true,connections,opacity:rawView?.9:1});if(state.trails&&hands[side])drawTrails(ctx,cameraHistory.recent(now),side,w,h,{now,lifetime:900,opacity:rawView?.9:.8});drawDotHand(ctx,hands[side],side,w,h,{connections});const detected=!!hands[side];$(`${side}-status`).classList.toggle('detected',detected);$(`${side}-status`).innerHTML=`<i></i> ${side==='left'?'左':'右'}手 · ${detected?'已识别':'未识别'}`;}
 const count=Number(!!hands.left)+Number(!!hands.right);$('camera-hint').textContent=state.frameGap>250?'识别帧率偏低，请保持页面在前台':count===2?'双手已识别 · 同色光点跟上空心目标':count===1?'只识别到一只手，请露出另一只手':'请同时举起左右手';
}
function updateScore(score,caption){const total=Math.round(score.total);$('total-score').textContent=total;$('score-caption').textContent=caption;$('ring').style.strokeDashoffset=207.35*(1-total/100);const values={left:typeof score.left==='number'?score.left:score.left.total,right:typeof score.right==='number'?score.right:score.right.total,coord:score.coordination,motion:score.motion};for(const [id,v]of Object.entries(values)){$(`${id}-score`).textContent=Math.round(v);$(`${id}-bar`).style.width=`${v}%`;}}
function resetScore(){$('total-score').textContent='—';$('score-caption').textContent='完成一轮后看成绩';$('ring').style.strokeDashoffset=207.35;for(const id of ['left','right','coord','motion']){$(`${id}-score`).textContent='—';$(`${id}-bar`).style.width='0%';}$('coverage').textContent='—';$('sampling').textContent='—';$('score-chip').textContent='等待练习';}
function endPractice(cancelled=false){
 state.practice=false;state.counting=false;clearTimeout(countTimer);$('countdown').hidden=true;$('practice').disabled=false;$('practice').innerHTML='再练一轮 <span>→</span>';state.playing=false;
 const report=summarizeSession(state.samples.filter(s=>s.received),0),quality=sessionQuality(state.samples,state.expected);
 if(report&&quality.enough){updateScore(report,cancelled?'本次已练段落':`${state.end-state.start} 拍练习已完成`);$('score-chip').textContent=cancelled?'练习已结束':'本轮成绩';$('score-help').textContent=quality.coverage<80?'双手漏检较多。保持双手完整入镜，交叉时错开前后层次，再试一轮。':report.coordination<65?'下一轮留意两只手之间的距离与高低关系，先慢放练习。':'可以尝试提高速度，保持双手呼应与转腕的流畅度。';}
 else if(!quality.enough){resetScore();$('score-chip').textContent='采样不足';$('score-caption').textContent='本轮暂不评分';$('score-help').textContent='识别帧率不足，采集不到连续动作。请关闭其他识别页面，在 Chrome / Edge 重试。';}
 else{resetScore();$('score-chip').textContent='无法评分';$('score-caption').textContent='本轮没有识别到手部';$('score-help').textContent='没有足够的手部识别数据。请检查光线与双手是否完整入镜，再练一轮。';}
 $('coverage').textContent=`${quality.coverage}%`;$('sampling').textContent=`${quality.sampling}%`;
 $('practice-note').textContent=cancelled?'练习提前结束，结果只覆盖已练段落。':'完成。左右手都识别到，才能拿到配合分。';syncPlayButton();
}
function syncPlayButton(){$('play').textContent=state.playing?'Ⅱ':'▶';$('play').setAttribute('aria-label',state.playing?'暂停示范':'播放示范');}
function setRoutine(phrase){if(state.practice||state.counting)endPractice(true);returnBeat=null;state.start=phrase?.start??0;state.end=phrase?.end??32;state.beat=state.start;state.playing=true;previous=null;lastClick=-1;$('seek').min=state.start;$('seek').max=state.end;document.querySelectorAll('.phrase-button').forEach(button=>button.classList.toggle('selected',button.dataset.phrase===phrase?.id));$('full-routine').classList.toggle('active',!phrase);$('practice-note').textContent=`${phrase?phrase.name+' · 8 拍':'完整 32 拍'}，倒数 3 秒后开始练习。`;syncPlayButton();}
function miniSvg(phrase){const a=sampleDuet(phrase.start+2),paths=['left','right'].map(side=>FINGERS.map(f=>{const points=f.chain.map(i=>`${a.points[side][i].x*100},${a.points[side][i].y*70-10}`).join(' '),p=a.points[side][f.tip],x=p.x*100,y=p.y*70-10;return `<polyline points="${points}" fill="none" stroke="${f.color}" stroke-opacity=".32" stroke-width=".55" stroke-linecap="round"/>`+(side==='left'?`<circle cx="${x}" cy="${y}" r="1.4" fill="${f.color}"/>`:`<path d="M${x},${y-1.7}l1.7,1.7l-1.7,1.7l-1.7,-1.7z" fill="${f.color}"/>`);}).join('')).join('');const all=[...a.points.left,...a.points.right],xs=all.map(p=>p.x*100),ys=all.map(p=>p.y*70-10),x=Math.min(...xs)-5,y=Math.min(...ys)-5;return `<svg viewBox="${x} ${y} ${Math.max(...xs)-x+5} ${Math.max(...ys)-y+5}" aria-hidden="true">${paths}</svg>`;}
$('finger-key').innerHTML=FINGERS.map(f=>`<span><b style="background:${f.color};color:#16231f">${f.number}</b>${f.name}</span>`).join('');$('framing').innerHTML=miniSvg(PHRASES[0]);
$('phrase-list').innerHTML=PHRASES.map((p,i)=>`<button class="phrase-button" data-phrase="${p.id}" aria-label="循环练习${p.name}"><span>0${i+1} / ${i*8+1}–${(i+1)*8} 拍</span><strong>${p.name}</strong>${miniSvg(p)}</button>`).join('');for(const button of document.querySelectorAll('.phrase-button'))button.onclick=()=>setRoutine(PHRASES.find(p=>p.id===button.dataset.phrase));$('full-routine').onclick=()=>setRoutine(null);
$('play').onclick=()=>{if(state.counting)return;if(state.beat>=state.end&&returnBeat===null)state.beat=state.start;state.playing=!state.playing;lastTime=performance.now();previous=null;syncPlayButton();};$('restart').onclick=()=>{if(state.practice||state.counting)endPractice(true);returnBeat=null;state.beat=state.start;state.playing=true;lastClick=-1;syncPlayButton();};$('seek').oninput=e=>{if(state.practice||state.counting)endPractice(true);returnBeat=null;state.beat=Number(e.target.value);state.playing=false;lastClick=-1;syncPlayButton();};$('speed').onchange=e=>{state.speed=Number(e.target.value);previous=null;};$('bpm').onchange=e=>{state.bpm=Number(e.target.value);previous=null;};$('loop').onchange=e=>state.loop=e.target.checked;$('trails').onclick=()=>{state.trails=!state.trails;$('trails').textContent=`拖尾 ${state.trails?'开':'关'}`;$('trails').setAttribute('aria-pressed',state.trails);};
$('connections').onclick=()=>{connections=!connections;$('connections').textContent=`手型线 ${connections?'开':'关'}`;$('connections').setAttribute('aria-pressed',connections);};
$('camera-view').onclick=()=>{rawView=!rawView;$('camera-stage').classList.toggle('light-view',!rawView);$('camera-stage').classList.toggle('raw-view',rawView);$('camera-view').textContent=rawView?'画面：原画':'画面：光点';$('camera-view').setAttribute('aria-pressed',!rawView);};
$('swap').onclick=()=>{state.swap=!state.swap;$('swap').setAttribute('aria-pressed',state.swap);$('swap').textContent=state.swap?'已交换左右':'交换左右';state.observed={left:null,right:null};cameraHistory.clear();previous=null;};
function enableCamera(){if(state.stream&&state.workerReady)return Promise.resolve(true);if(cameraPromise)return cameraPromise;cameraPromise=startCamera().finally(()=>cameraPromise=null);return cameraPromise;}
async function startCamera(){$('enable-camera').disabled=true;$('camera-status').textContent='加载双手识别…';try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('请在 localhost 或 HTTPS 页面打开原型。');state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:864},aspectRatio:{ideal:1.48}},audio:false});$('camera').srcObject=state.stream;await $('camera').play();await initWorker();$('camera-status').textContent='识别预热中…';await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('未收到摄像头识别结果，请重试。')),20000);firstFrameResolve=()=>{clearTimeout(timeout);firstFrameResolve=null;resolve();};});$('camera-placeholder').hidden=true;$('camera-legend').hidden=false;$('camera-hint').hidden=false;$('stop-camera').hidden=false;return true;}catch(error){stopCamera();$('camera-status').textContent='摄像头未就绪';$('practice-note').textContent=`无法开启：${error.message}`;showNotice(`无法开启摄像头：${error.message}`);return false;}finally{$('enable-camera').disabled=false;}}
function initWorker(){if(state.workerReady)return Promise.resolve();if(worker)worker.terminate();worker=new Worker('./tracker-worker.mjs');state.lastDetection=0;state.frameGap=0;return new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('识别模型加载超时，请重试。')),30000);worker.onmessage=event=>{const data=event.data;if(data.type==='ready'){clearTimeout(timeout);state.workerReady=true;resolve();}else if(data.type==='result'){busy=false;const now=performance.now();state.frameGap=state.lastDetection?now-state.lastDetection:0;state.lastDetection=now;const video=$('camera');state.observed=projectHands(identifyHands(data,{mirror:true,swap:state.swap}),video.videoWidth/video.videoHeight);cameraHistory.push(now,state.observed);$('camera-status').dataset.inferenceMs=Math.round(data.inferenceMs);$('camera-status').textContent=`${data.landmarks.length} 只手 · ${state.frameGap?Math.round(1000/state.frameGap):'—'} FPS`;firstFrameResolve?.();advanceClock(now);recordDetection(data.timestamp,now);}else if(data.type==='error'){busy=false;if(!state.workerReady){clearTimeout(timeout);reject(new Error(data.message));}else{$('camera-status').textContent='识别暂时失败';state.observed={left:null,right:null};}}};worker.onerror=error=>{busy=false;clearTimeout(timeout);reject(new Error(error.message||'识别进程启动失败'));};worker.postMessage({type:'init'});});}
function stopCamera(){if(state.practice||state.counting)endPractice(true);state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;worker?.terminate();worker=null;state.workerReady=false;busy=false;state.observed={left:null,right:null};cameraHistory.clear();$('camera').srcObject=null;$('camera-placeholder').hidden=false;$('camera-legend').hidden=true;$('camera-hint').hidden=true;$('stop-camera').hidden=true;$('camera-status').textContent='摄像头未开启';for(const side of ['left','right']){$(`${side}-status`).classList.remove('detected');$(`${side}-status`).innerHTML=`<i></i> ${side==='left'?'左':'右'}手 · 待识别`;}}
$('enable-camera').onclick=enableCamera;$('stop-camera').onclick=stopCamera;
$('practice').onclick=async()=>{if(state.practice||state.counting){endPractice(true);return;}$('practice').disabled=true;const ok=await enableCamera();if(!ok){$('practice').disabled=false;return;}state.playing=false;returnBeat=null;state.beat=state.start;state.counting=true;state.samples=[];state.expected=0;state.elapsed=0;previous=null;resetScore();$('score-chip').textContent='准备开始';$('practice').disabled=false;$('practice').innerHTML='结束练习 <span>■</span>';$('countdown').hidden=false;let n=3;const count=()=>{if(!state.counting)return;if(document.hidden){countTimer=setTimeout(count,300);return;}$('countdown').textContent=n;if(n--===0){state.counting=false;$('countdown').hidden=true;state.practice=true;state.playing=true;lastTime=performance.now();lastSample=lastTime;lastClick=-1;$('score-chip').textContent='实时估计';$('practice-note').textContent='同色指尖跟上空心目标，左右手要同时入镜。';syncPlayButton();return;}countTimer=setTimeout(count,1000);};count();};
$('metronome').onclick=async()=>{try{audio??=new AudioContext();await audio.resume();metro=!metro;$('metronome').textContent=`♩ 节拍器 ${metro?'开':'关'}`;$('metronome').setAttribute('aria-pressed',metro);lastClick=-1;}catch(error){showNotice(`节拍器不可用：${error.message}`);}};
function clickBeat(beat){if(!metro||!audio)return;const n=Math.floor(beat);if(n===lastClick)return;lastClick=n;const osc=audio.createOscillator(),gain=audio.createGain();osc.frequency.value=n%4===0?1050:710;gain.gain.setValueAtTime(.08,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.065);osc.connect(gain).connect(audio.destination);osc.start();osc.stop(audio.currentTime+.07);}
async function requestFrame(now){if(!state.stream||!state.workerReady||busy||now-lastFrame<66||$('camera').readyState<2)return;lastFrame=now;busy=true;const captureStart=performance.now();try{const video=$('camera'),width=Math.min(640,video.videoWidth),bitmap=await createImageBitmap(video,{resizeWidth:width,resizeHeight:Math.round(width*video.videoHeight/video.videoWidth)});$('camera-status').dataset.captureMs=Math.round(performance.now()-captureStart);if(!worker){bitmap.close();busy=false;return;}worker.postMessage({type:'frame',bitmap,timestamp:now},[bitmap]);}catch{busy=false;state.observed={left:null,right:null};}}
function advanceClock(now){const dt=Math.max(0,(now-lastTime)/1000);lastTime=now;if(!state.playing)return;const rate=state.bpm/60*state.speed;if(state.practice){state.elapsed+=Math.min(dt,Math.max(0,(state.end-state.beat)/rate));state.expected=Math.ceil(state.elapsed*10-1e-6);const missing=evaluateDuet({left:null,right:null},sampleDuet(state.beat));while(state.samples.length<state.expected)state.samples.push(missing);}if(returnBeat!==null){returnBeat+=dt*rate;if(returnBeat>=1){returnBeat=null;state.beat=state.start;lastClick=-1;}}else{state.beat+=dt*rate;if(state.beat>=state.end){state.beat=state.end;if(state.practice)endPractice();else if(state.loop){returnBeat=0;lastClick=-1;}else{state.playing=false;syncPlayButton();}}}if(state.playing&&returnBeat===null)clickBeat(state.beat);}
function recordDetection(timestamp,received){if(!state.practice||!state.playing||timestamp<=lastSample)return;const lag=Math.max(0,(received-timestamp)/1000),elapsed=Math.max(0,state.elapsed-lag),index=Math.floor(elapsed*10);if(index>=state.expected)return;const target=sampleDuet(Math.max(state.start,state.beat-lag*state.bpm/60*state.speed)),observed={...state.observed},score=evaluateDuet(observed,target,previous,(timestamp-lastSample)/1000);score.received=true;state.samples[index]=score;previous={observed,target};lastSample=timestamp;updateScore(score,score.both?'当前帧 · 双手估计':score.trackedCount?'另一只手未识别':'双手未识别');const quality=sessionQuality(state.samples,state.expected);$('sampling').textContent=`${quality.sampling}%`;$('coverage').textContent=`${quality.coverage}%`;}
let lastPhrase='',lastRender='',lastOverlay='',lastRenderTime=0,lastOverlayTime=0;function animate(now){advanceClock(now);const target=returnBeat===null?sampleDuet(state.beat):returnToStart(state.end,state.start,returnBeat);if(state.end-state.start===8)target.phrase=PHRASES.find(p=>p.start===state.start);const signature=[state.beat,returnBeat,state.trails,connections,$('demo-canvas').clientWidth,$('demo-canvas').clientHeight].join('|');if(signature!==lastRender&&now-lastRenderTime>=33){lastRenderTime=now;scene.update(target,{history:demoHistory(),trails:state.trails,connections});renderPaths(target);lastRender=signature;}const overlay=[signature,state.lastDetection,state.stream?.id??'',state.swap,rawView,Math.floor(now/33),$('camera-overlay').clientWidth].join('|');if(now-lastOverlayTime>=50&&(overlay!==lastOverlay||now-state.lastDetection>2000)){lastOverlayTime=now;updateCamera(target);lastOverlay=overlay;}
 $('seek').value=state.beat;$('beat-label').textContent=`${String(Math.min(state.end,Math.floor(state.beat)+1)).padStart(2,'0')} / ${state.end} 拍`;$('progress-label').textContent=`${Math.min(state.end-state.start,Math.floor(state.beat-state.start)+1)} / ${state.end-state.start} 拍`;$('cue').textContent=returnBeat===null&&state.beat===state.end&&state.end-state.start===8?'本段完成':target.cue;
 if(lastPhrase!==target.phrase.id){lastPhrase=target.phrase.id;$('phrase-badge').textContent=target.phrase.name;$('motion-note').textContent=target.phrase.description;$('left-instruction').textContent=target.phrase.left;$('right-instruction').textContent=target.phrase.right;$('detail').textContent=target.phrase.detail;document.querySelectorAll('.phrase-button').forEach(b=>b.classList.toggle('playing',b.dataset.phrase===target.phrase.id));}
 requestAnimationFrame(animate);}
const cameraTimer=setInterval(()=>{const now=performance.now();advanceClock(now);requestFrame(now);},66);document.addEventListener('visibilitychange',()=>{if(document.hidden){state.playing=false;previous=null;syncPlayButton();}lastTime=performance.now();});window.addEventListener('beforeunload',()=>{clearInterval(cameraTimer);state.stream?.getTracks().forEach(t=>t.stop());worker?.terminate();});syncPlayButton();requestAnimationFrame(animate);

